using System.Globalization;
using System.Numerics;
using System.Text;
using DotRecast.Recast;
using vnavmesh.Common.Navigation.Mesh.Runtime;
using vnavmesh.Navigation.Scene;

namespace vnavmesh.Navigation.Customizations.Editor;

internal sealed record CustomizationDraftExportResult
(
    FileInfo File,
    string   ClassName,
    int      Version,
    string   ContentHash
);

internal static class CustomizationDraftExporter
{
    public static CustomizationDraftExportResult Export(CustomizationDraft draft, DirectoryInfo outputDirectory)
    {
        outputDirectory.Create();

        var className = BuildClassName(draft);
        var file      = new FileInfo(Path.Combine(outputDirectory.FullName, $"{className}.generated.cs"));
        var source    = GenerateSource(draft, className);
        File.WriteAllText(file.FullName, source, new UTF8Encoding(false));

        return new(file, className, draft.ComputeVersion(), draft.ComputeContentHash());
    }

    public static string GenerateSource(CustomizationDraft draft, string? className = null)
    {
        className ??= BuildClassName(draft);

        var sb = new StringBuilder(8192);
        Line(sb, 0, "using System.Collections.Generic;");
        Line(sb, 0, "using System.Numerics;");
        Line(sb, 0, "using DotRecast.Detour;");
        Line(sb, 0, "using DotRecast.Recast;");
        Line(sb, 0, "using FFXIVClientStructs.FFXIV.Common.Component.BGCollision.Math;");
        Line(sb, 0, "using vnavmesh.Common.Navigation.Mesh.Runtime;");
        Line(sb, 0, "using vnavmesh.Navigation.Customizations;");
        Line(sb, 0, "using vnavmesh.Navigation.Customizations.Attributes;");
        Line(sb, 0, "using vnavmesh.Navigation.Customizations.Extensions;");
        Line(sb, 0, "using vnavmesh.Navigation.Mesh.Build;");
        Line(sb, 0, "using vnavmesh.Navigation.Mesh.Runtime;");
        Line(sb, 0, "using vnavmesh.Navigation.Scene;");
        Line(sb);
        Line(sb, 0, "namespace vnavmesh.Navigation.Customizations.Territories.Generated;");
        Line(sb);
        Line(sb, 0, $"// Generated by vnavmesh 自定义编辑器. Territory={draft.TerritoryID} {draft.DisplayName}, hash={draft.ComputeContentHash()[..16]}.");
        Line(sb, 0, "// 如果同一 Territory 已有手写自定义, 先人工合并或移除旧类, 不要直接编译两个同 ID 自定义.");
        Line(sb, 0, $"[CustomizationTerritory({draft.TerritoryID})]");
        Line(sb, 0, $"internal class {className} : NavmeshCustomization");
        Line(sb, 0, "{");
        Line(sb, 1, $"public override int Version => {draft.ComputeVersion().ToString(CultureInfo.InvariantCulture)};");
        Line(sb);

        if (draft.FlyingSupportedOverride is { } flyable)
        {
            Line(sb, 1, $"public override bool IsFlyingSupported(SceneDefinition definition) => {FormatBool(flyable)};");
            Line(sb);
        }

        AppendBuildProfileMethod(sb, draft.BuildProfile);
        AppendBuildSettingsMethod(sb, draft.BuildSettings);
        AppendSceneMethod(sb, draft);
        AppendSettingsMethod(sb, draft);
        AppendMeshMethod(sb, draft);
        AppendHelpers(sb, draft);

        Line(sb, 0, "}");
        return NormalizeLineEndings(sb.ToString());
    }

    private static void AppendBuildProfileMethod(StringBuilder sb, DraftBuildProfileOverrides profile)
    {
        var body = new StringBuilder();
        AppendAssignment(body, 2, "profile.PartitioningOverride",               profile.PartitioningOverride,               FormatRcPartition);
        AppendAssignment(body, 2, "profile.CellSizeOverride",                   profile.CellSizeOverride,                   FormatFloat);
        AppendAssignment(body, 2, "profile.CellHeightOverride",                 profile.CellHeightOverride,                 FormatFloat);
        AppendAssignment(body, 2, "profile.RegionMinSizeOverride",              profile.RegionMinSizeOverride,              FormatFloat);
        AppendAssignment(body, 2, "profile.RegionMergeSizeOverride",            profile.RegionMergeSizeOverride,            FormatFloat);
        AppendAssignment(body, 2, "profile.PolyMaxEdgeLenOverride",             profile.PolyMaxEdgeLenOverride,             FormatFloat);
        AppendAssignment(body, 2, "profile.PolyMaxSimplificationErrorOverride", profile.PolyMaxSimplificationErrorOverride, FormatFloat);
        AppendAssignment(body, 2, "profile.AgentRadiusOverride",                profile.AgentRadiusOverride,                FormatFloat);
        AppendAssignment(body, 2, "profile.VolumeTilesOverride",                profile.VolumeTilesOverride,                FormatIntArray);
        AppendAssignment(body, 2, "profile.DetailSampleDistOverride",           profile.DetailSampleDistOverride,           FormatFloat);
        AppendAssignment(body, 2, "profile.GenerateEdgeClimbLinksOverride",     profile.GenerateEdgeClimbLinksOverride,     FormatBool);
        AppendAssignment(body, 2, "profile.GenerateEdgeJumpLinksOverride",      profile.GenerateEdgeJumpLinksOverride,      FormatBool);

        if (body.Length == 0)
            return;

        Line(sb, 1, "public override void CustomizeBuildProfile(SceneDefinition definition, NavmeshBuildProfile profile)");
        Line(sb, 1, "{");
        sb.Append(body);
        Line(sb, 1, "}");
        Line(sb);
    }

    private static void AppendBuildSettingsMethod(StringBuilder sb, DraftBuildSettingsOverrides settings)
    {
        var body = new StringBuilder();
        AppendAssignment(body, 2, "settings.CellSize",                   settings.CellSize,                   FormatFloat);
        AppendAssignment(body, 2, "settings.CellHeight",                 settings.CellHeight,                 FormatFloat);
        AppendAssignment(body, 2, "settings.AgentHeight",                settings.AgentHeight,                FormatFloat);
        AppendAssignment(body, 2, "settings.AgentRadius",                settings.AgentRadius,                FormatFloat);
        AppendAssignment(body, 2, "settings.AgentMaxClimb",              settings.AgentMaxClimb,              FormatFloat);
        AppendAssignment(body, 2, "settings.AgentMaxSlopeDeg",           settings.AgentMaxSlopeDeg,           FormatFloat);
        AppendAssignment(body, 2, "settings.Filtering",                  settings.Filtering,                  FormatNavmeshFilter);
        AppendAssignment(body, 2, "settings.RegionMinSize",              settings.RegionMinSize,              FormatFloat);
        AppendAssignment(body, 2, "settings.RegionMergeSize",            settings.RegionMergeSize,            FormatFloat);
        AppendAssignment(body, 2, "settings.Partitioning",               settings.Partitioning,               FormatRcPartition);
        AppendAssignment(body, 2, "settings.PolyMaxEdgeLen",             settings.PolyMaxEdgeLen,             FormatFloat);
        AppendAssignment(body, 2, "settings.PolyMaxSimplificationError", settings.PolyMaxSimplificationError, FormatFloat);
        AppendAssignment(body, 2, "settings.PolyMaxVerts",               settings.PolyMaxVerts,               FormatInt);
        AppendAssignment(body, 2, "settings.DetailSampleDist",           settings.DetailSampleDist,           FormatFloat);
        AppendAssignment(body, 2, "settings.DetailMaxSampleError",       settings.DetailMaxSampleError,       FormatFloat);
        AppendAssignment(body, 2, "settings.FastBuild",                  settings.FastBuild,                  FormatBool);
        AppendAssignment(body, 2, "settings.GenerateEdgeClimbLinks",     settings.GenerateEdgeClimbLinks,     FormatBool);
        AppendAssignment(body, 2, "settings.GenerateEdgeJumpLinks",      settings.GenerateEdgeJumpLinks,      FormatBool);
        AppendAssignment(body, 2, "settings.GroundTolerance",            settings.GroundTolerance,            FormatFloat);
        AppendAssignment(body, 2, "settings.ClimbDownDistance",          settings.ClimbDownDistance,          FormatFloat);
        AppendAssignment(body, 2, "settings.ClimbDownMaxHeight",         settings.ClimbDownMaxHeight,         FormatFloat);
        AppendAssignment(body, 2, "settings.ClimbDownMinHeight",         settings.ClimbDownMinHeight,         FormatFloat);
        AppendAssignment(body, 2, "settings.EdgeJumpEndDistance",        settings.EdgeJumpEndDistance,        FormatFloat);
        AppendAssignment(body, 2, "settings.EdgeJumpHeight",             settings.EdgeJumpHeight,             FormatFloat);
        AppendAssignment(body, 2, "settings.EdgeJumpMaxDrop",            settings.EdgeJumpMaxDrop,            FormatFloat);
        AppendAssignment(body, 2, "settings.EdgeJumpMinDrop",            settings.EdgeJumpMinDrop,            FormatFloat);
        AppendAssignment(body, 2, "settings.GroundTileSize",             settings.GroundTileSize,             FormatFloat);
        AppendAssignment(body, 2, "settings.GroundTileCountMax",         settings.GroundTileCountMax,         FormatInt);
        AppendAssignment(body, 2, "settings.VolumeTiles",                settings.VolumeTiles,                FormatIntArray);

        if (body.Length == 0)
            return;

        Line(sb, 1, "public override void CustomizeBuildSettings(SceneDefinition definition, NavmeshSettings settings)");
        Line(sb, 1, "{");
        sb.Append(body);
        Line(sb, 1, "}");
        Line(sb);
    }

    private static void AppendSceneMethod(StringBuilder sb, CustomizationDraft draft)
    {
        var body = new StringBuilder();

        foreach (var removal in draft.MeshRemovals.Where(static x => x.Enabled))
            Line(body, 2, $"scene.Meshes.Remove(\"{Escape(removal.MeshKey)}\");");

        foreach (var patch in draft.PartPatches.Where(static x => x.Enabled))
            AppendPartPatch(body, patch);

        foreach (var patch in draft.InstancePatches.Where(static x => x.Enabled))
            AppendInstancePatch(body, patch);

        foreach (var insertion in draft.ColliderInsertions.Where(static x => x.Enabled))
            AppendColliderInsertion(body, insertion);

        if (body.Length == 0)
            return;

        Line(sb, 1, "public override void CustomizeScene(SceneExtractor scene)");
        Line(sb, 1, "{");
        sb.Append(body);
        Line(sb, 1, "}");
        Line(sb);
    }

    private static void AppendSettingsMethod(StringBuilder sb, CustomizationDraft draft)
    {
        var links = draft.OffMeshConnections.Where(static x => x.Enabled).ToArray();
        if (links.Length == 0)
            return;

        Line(sb, 1, "public override void CustomizeSettings(DtNavMeshCreateParams config)");
        Line(sb, 1, "{");

        foreach (var link in links)
        {
            var area  = FormatEnum(link.Area, "NavmeshArea");
            var flags = FormatNavmeshPolyFlags(link.Flags);
            var kind  = FormatEnum(link.Kind, "NavmeshOffMeshKind");

            Line(sb, 2, "config.AddOffMeshConnection");
            Line(sb, 2, "(");
            Line(sb, 3, $"{FormatVector(link.Start)},");
            Line(sb, 3, $"{FormatVector(link.End)},");
            Line(sb, 3, $"{FormatFloat(link.Radius)},");
            Line(sb, 3, $"{FormatBool(link.Bidirectional)},");
            Line(sb, 3, $"{FormatInt(link.UserId)},");
            Line(sb, 3, $"{area},");
            Line(sb, 3, $"{flags},");
            Line(sb, 3, kind);
            Line(sb, 2, ");");
        }

        Line(sb, 1, "}");
        Line(sb);
    }

    private static void AppendMeshMethod(StringBuilder sb, CustomizationDraft draft)
    {
        var links = draft.MeshLinks.Where(static x => x.Enabled).ToArray();
        if (links.Length == 0)
            return;

        Line(sb, 1, "public override void CustomizeMesh(Navmesh mesh, List<uint> festivalLayers)");
        Line(sb, 1, "{");

        foreach (var link in links)
        {
            var call = link.Kind switch
            {
                DraftMeshLinkKind.Points     => "LinkPoints",
                DraftMeshLinkKind.Drop       => "LinkDrop",
                DraftMeshLinkKind.ClientPath => "LinkClientPath",
                _                            => "LinkPoints"
            };
            Line(sb, 2, $"{call}(mesh, {FormatVector(link.Start)}, {FormatVector(link.End)});");
        }

        Line(sb, 1, "}");
        Line(sb);
    }

    private static void AppendPartPatch(StringBuilder sb, DraftScenePartPatch patch)
    {
        Line(sb, 2, $"if (scene.Meshes.TryGetValue(\"{Escape(patch.MeshKey)}\", out var mesh))");
        Line(sb, 2, "{");
        Line(sb, 3, $"if ({patch.PartIndex} >= 0 && {patch.PartIndex} < mesh.Parts.Count)");
        Line(sb, 3, "{");
        Line(sb, 4, $"var part = mesh.Parts[{patch.PartIndex}];");

        switch (patch.Kind)
        {
            case DraftScenePartPatchKind.Vertex:
                Line(sb, 4, $"if ({patch.VertexIndex} >= 0 && {patch.VertexIndex} < part.Vertices.Count)");
                Line(sb, 4, "{");
                Line(sb, 5, $"part.Vertices[{patch.VertexIndex}] = {FormatVector(patch.Position)};");
                Line(sb, 5, "part.LocalBounds = CalculateLocalBounds(part.Vertices);");
                Line(sb, 5, "RecalculateMeshBounds(mesh);");
                Line(sb, 4, "}");
                break;
            case DraftScenePartPatchKind.PrimitiveFlags:
                Line(sb, 4, $"if ({patch.PrimitiveIndex} >= 0 && {patch.PrimitiveIndex} < part.Primitives.Count)");
                Line(sb, 4, "{");
                Line(sb, 5, $"var primitive = part.Primitives[{patch.PrimitiveIndex}];");
                Line(sb, 5, $"primitive.Flags = {FormatPrimitiveFlags(patch.Flags)};");
                Line(sb, 5, $"part.Primitives[{patch.PrimitiveIndex}] = primitive;");
                Line(sb, 4, "}");
                break;
            case DraftScenePartPatchKind.PrimitiveEdit:
                Line(sb, 4, $"if ({patch.PrimitiveIndex} >= 0 && {patch.PrimitiveIndex} < part.Primitives.Count)");
                Line(sb, 4, "{");
                Line
                (
                    sb,
                    5,
                    $"part.Primitives[{patch.PrimitiveIndex}] = new({patch.V1}, {patch.V2}, {patch.V3}, {FormatPrimitiveFlags(patch.Flags)}, {FormatUlong(patch.Material)});"
                );
                Line(sb, 4, "}");
                break;
        }

        Line(sb, 3, "}");
        Line(sb, 2, "}");
    }

    private static void AppendInstancePatch(StringBuilder sb, DraftSceneInstancePatch patch)
    {
        Line(sb, 2, $"if (scene.Meshes.TryGetValue(\"{Escape(patch.MeshKey)}\", out var mesh))");
        Line(sb, 2, "{");

        switch (patch.Kind)
        {
            case DraftSceneInstancePatchKind.ClearInstances:
                Line(sb, 3, "mesh.Instances.Clear();");
                break;
            case DraftSceneInstancePatchKind.RemoveInstance:
                Line(sb, 3, $"var index = ResolveInstanceIndex(mesh, {FormatUlong(patch.InstanceId)}, {patch.InstanceIndex});");
                Line(sb, 3, "if (index >= 0)");
                Line(sb, 4, "mesh.Instances.RemoveAt(index);");
                break;
            case DraftSceneInstancePatchKind.Transform:
                Line(sb, 3, $"if (ResolveInstance(mesh, {FormatUlong(patch.InstanceId)}, {patch.InstanceIndex}) is {{ }} inst)");
                Line(sb, 3, "{");
                Line(sb, 4, $"inst.WorldTransform.Row0 = {FormatVector(patch.WorldTransform.Row0)};");
                Line(sb, 4, $"inst.WorldTransform.Row1 = {FormatVector(patch.WorldTransform.Row1)};");
                Line(sb, 4, $"inst.WorldTransform.Row2 = {FormatVector(patch.WorldTransform.Row2)};");
                Line(sb, 4, $"inst.WorldTransform.Row3 = {FormatVector(patch.WorldTransform.Row3)};");
                Line(sb, 4, "inst.WorldBounds = TransformBounds(inst.WorldTransform, mesh.LocalBounds);");
                Line(sb, 3, "}");
                break;
            case DraftSceneInstancePatchKind.SetFlags:
                Line(sb, 3, $"if (ResolveInstance(mesh, {FormatUlong(patch.InstanceId)}, {patch.InstanceIndex}) is {{ }} inst)");
                Line(sb, 3, "{");
                Line(sb, 4, $"inst.ForceSetPrimFlags = {FormatPrimitiveFlags(patch.ForceSetPrimFlags)};");
                Line(sb, 4, $"inst.ForceClearPrimFlags = {FormatPrimitiveFlags(patch.ForceClearPrimFlags)};");
                Line(sb, 3, "}");
                break;
        }

        Line(sb, 2, "}");
    }

    private static void AppendColliderInsertion(StringBuilder sb, DraftSceneColliderInsertion insertion)
    {
        var min  = Vector3.Min(insertion.Min, insertion.Max);
        var max  = Vector3.Max(insertion.Min, insertion.Max);
        var call = insertion.Kind == DraftSceneColliderInsertionKind.Cylinder ? "InsertCylinderCollider" : "InsertAABoxCollider";

        Line(sb, 2, "scene." + call);
        Line(sb, 2, "(");
        Line(sb, 3, "new AABB");
        Line(sb, 3, "{");
        Line(sb, 4, $"Min = {FormatVector(min)},");
        Line(sb, 4, $"Max = {FormatVector(max)}");
        Line(sb, 3, "},");
        Line(sb, 3, $"{FormatPrimitiveFlags(insertion.ForceSetPrimFlags)},");
        Line(sb, 3, $"{FormatPrimitiveFlags(insertion.ForceClearPrimFlags)}");
        Line(sb, 2, ");");
    }

    private static void AppendHelpers(StringBuilder sb, CustomizationDraft draft)
    {
        var needsInstanceHelpers = draft.InstancePatches.Any(static x => x.Enabled && x.Kind != DraftSceneInstancePatchKind.ClearInstances);
        var needsBoundsHelpers = draft.InstancePatches.Any(static x => x is { Enabled: true, Kind: DraftSceneInstancePatchKind.Transform }) ||
                                 draft.PartPatches.Any(static x => x is { Enabled: true, Kind: DraftScenePartPatchKind.Vertex });

        if (needsInstanceHelpers)
        {
            Line(sb, 1, "private static SceneExtractor.MeshInstance? ResolveInstance(SceneExtractor.Mesh mesh, ulong instanceId, int instanceIndex)");
            Line(sb, 1, "{");
            Line(sb, 2, "var index = ResolveInstanceIndex(mesh, instanceId, instanceIndex);");
            Line(sb, 2, "return index >= 0 ? mesh.Instances[index] : null;");
            Line(sb, 1, "}");
            Line(sb);

            Line(sb, 1, "private static int ResolveInstanceIndex(SceneExtractor.Mesh mesh, ulong instanceId, int instanceIndex)");
            Line(sb, 1, "{");
            Line(sb, 2, "if (instanceId != 0)");
            Line(sb, 2, "{");
            Line(sb, 3, "for (var i = 0; i < mesh.Instances.Count; ++i)");
            Line(sb, 3, "{");
            Line(sb, 4, "if (mesh.Instances[i].Id == instanceId)");
            Line(sb, 5, "return i;");
            Line(sb, 3, "}");
            Line(sb, 2, "}");
            Line(sb);
            Line(sb, 2, "return instanceIndex >= 0 && instanceIndex < mesh.Instances.Count ? instanceIndex : -1;");
            Line(sb, 1, "}");
            Line(sb);
        }

        if (!needsBoundsHelpers)
            return;

        Line(sb, 1, "private static void RecalculateMeshBounds(SceneExtractor.Mesh mesh)");
        Line(sb, 1, "{");
        Line(sb, 2, "mesh.LocalBounds = CalculateLocalBounds(mesh.Parts);");
        Line(sb, 2, "foreach (var instance in mesh.Instances)");
        Line(sb, 3, "instance.WorldBounds = TransformBounds(instance.WorldTransform, mesh.LocalBounds);");
        Line(sb, 1, "}");
        Line(sb);

        Line(sb, 1, "private static AABB CalculateLocalBounds(List<SceneExtractor.MeshPart> parts)");
        Line(sb, 1, "{");
        Line(sb, 2, "var bounds = new AABB { Min = new(float.MaxValue), Max = new(float.MinValue) };");
        Line(sb, 2, "foreach (var part in parts)");
        Line(sb, 2, "{");
        Line(sb, 3, "bounds.Min = Vector3.Min(bounds.Min, part.LocalBounds.Min);");
        Line(sb, 3, "bounds.Max = Vector3.Max(bounds.Max, part.LocalBounds.Max);");
        Line(sb, 2, "}");
        Line(sb, 2, "return bounds;");
        Line(sb, 1, "}");
        Line(sb);

        Line(sb, 1, "private static AABB CalculateLocalBounds(List<Vector3> vertices)");
        Line(sb, 1, "{");
        Line(sb, 2, "var bounds = new AABB { Min = new(float.MaxValue), Max = new(float.MinValue) };");
        Line(sb, 2, "foreach (var vertex in vertices)");
        Line(sb, 2, "{");
        Line(sb, 3, "bounds.Min = Vector3.Min(bounds.Min, vertex);");
        Line(sb, 3, "bounds.Max = Vector3.Max(bounds.Max, vertex);");
        Line(sb, 2, "}");
        Line(sb, 2, "return bounds;");
        Line(sb, 1, "}");
        Line(sb);

        Line(sb, 1, "private static AABB TransformBounds(Matrix4x3 worldTransform, AABB localBounds)");
        Line(sb, 1, "{");
        Line(sb, 2, "var localCenter = (localBounds.Min + localBounds.Max) * 0.5f;");
        Line(sb, 2, "var localExtent = (localBounds.Max - localBounds.Min) * 0.5f;");
        Line(sb, 2, "var axisX = worldTransform.Row0;");
        Line(sb, 2, "var axisY = worldTransform.Row1;");
        Line(sb, 2, "var axisZ = worldTransform.Row2;");
        Line(sb, 2, "var center = axisX * localCenter.X + axisY * localCenter.Y + axisZ * localCenter.Z + worldTransform.Row3;");
        Line(sb, 2, "var extent = Abs(axisX) * localExtent.X + Abs(axisY) * localExtent.Y + Abs(axisZ) * localExtent.Z;");
        Line(sb, 2, "return new() { Min = center - extent, Max = center + extent };");
        Line(sb, 1, "}");
        Line(sb);

        Line(sb, 1, "private static Vector3 Abs(Vector3 value) => new(MathF.Abs(value.X), MathF.Abs(value.Y), MathF.Abs(value.Z));");
        Line(sb);
    }

    private static void AppendAssignment<T>(StringBuilder sb, int indent, string target, T? value, Func<T, string> formatter) where T : struct
    {
        if (value is { } unwrapped)
            Line(sb, indent, $"{target} = {formatter(unwrapped)};");
    }

    private static void AppendAssignment(StringBuilder sb, int indent, string target, int[]? value, Func<int[], string> formatter)
    {
        if (value != null)
            Line(sb, indent, $"{target} = {formatter(value)};");
    }

    private static string BuildClassName(CustomizationDraft draft)
    {
        var suffix = SanitizeIdentifier(draft.TerritoryName);
        if (suffix.Length == 0)
            suffix = "Territory";

        return $"Z{draft.TerritoryID:D4}{suffix}EditorDraft";
    }

    private static string SanitizeIdentifier(string value)
    {
        var sb             = new StringBuilder(value.Length);
        var capitalizeNext = true;

        foreach (var ch in value)
        {
            switch (ch)
            {
                case >= 'a' and <= 'z':
                    sb.Append(capitalizeNext ? char.ToUpperInvariant(ch) : ch);
                    capitalizeNext = false;
                    break;
                case >= 'A' and <= 'Z' or >= '0' and <= '9':
                    sb.Append(ch);
                    capitalizeNext = false;
                    break;
                default:
                    capitalizeNext = true;
                    break;
            }
        }

        return sb.ToString();
    }

    private static string FormatFloat(float value)
    {
        if (float.IsNaN(value))
            return "float.NaN";
        if (float.IsPositiveInfinity(value))
            return "float.PositiveInfinity";
        if (float.IsNegativeInfinity(value))
            return "float.NegativeInfinity";

        return value.ToString("R", CultureInfo.InvariantCulture) + "f";
    }

    private static string FormatInt(int value) => value.ToString(CultureInfo.InvariantCulture);

    private static string FormatUlong(ulong value) => $"0x{value.ToString("X", CultureInfo.InvariantCulture)}ul";

    private static string FormatBool(bool value) => value ? "true" : "false";

    private static string FormatVector(Vector3 value) =>
        $"new({FormatFloat(value.X)}, {FormatFloat(value.Y)}, {FormatFloat(value.Z)})";

    private static string FormatIntArray(int[] value) =>
        $"new[] {{ {string.Join(", ", value.Select(static x => x.ToString(CultureInfo.InvariantCulture)))} }}";

    private static string FormatRcPartition(RcPartition value) => FormatEnum(value, "RcPartition");

    private static string FormatPrimitiveFlags(SceneExtractor.PrimitiveFlags value) =>
        FormatFlags(value, "SceneExtractor.PrimitiveFlags");

    private static string FormatNavmeshPolyFlags(NavmeshPolyFlags value) =>
        FormatFlags(value, "NavmeshPolyFlags");

    private static string FormatNavmeshFilter(NavmeshFilter value) =>
        FormatFlags(value, "NavmeshFilter");

    private static string FormatEnum<T>(T value, string prefix) where T : struct, Enum =>
        Enum.IsDefined(typeof(T), value)
            ? $"{prefix}.{value}"
            : $"({prefix}){Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture)}";

    private static string FormatFlags<T>(T value, string prefix) where T : struct, Enum
    {
        var raw = Convert.ToInt64(value, CultureInfo.InvariantCulture);
        if (raw == 0)
            return $"{prefix}.None";

        var          combined = 0L;
        List<string> parts    = [];

        foreach (var flag in Enum.GetValues<T>())
        {
            var current = Convert.ToInt64(flag, CultureInfo.InvariantCulture);
            if (current == 0 || (raw & current) != current)
                continue;

            combined |= current;
            parts.Add($"{prefix}.{flag}");
        }

        return combined == raw && parts.Count > 0 ? string.Join(" | ", parts) : $"({prefix}){raw.ToString(CultureInfo.InvariantCulture)}";
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

    private static string NormalizeLineEndings(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal).Replace("\r", "\n", StringComparison.Ordinal);

    private static void Line(StringBuilder sb, int indent = 0, string text = "")
    {
        if (text.Length > 0)
            sb.Append(' ', indent * 4).Append(text);
        sb.Append('\n');
    }
}
